name: trak_app
description: Trak carbon tracking app with gamification elements
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.5
  flutter_material_symbols: ^0.0.5
  percent_indicator: ^4.2.3
  fl_chart: ^0.63.0
  cached_network_image: ^3.2.3
  image_picker: ^1.0.1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/